FROM golang:1.25-alpine3.21 AS builder

WORKDIR /src/bitrise-webhooks

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY . .

# Build the binaries.
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /go/bin/bitrise-webhooks


FROM alpine:3.22

RUN apk add -u ca-certificates && rm -rf /var/cache/apk/*

EXPOSE 4000

COPY --from=builder /go/bin/bitrise-webhooks .

CMD ["/bitrise-webhooks"]
