
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

# Heroku specific
# https://github.com/heroku/heroku-buildpack-go#dep-specifics
[metadata.heroku]
  root-package = "github.com/bitrise-io/bitrise-webhooks"
  # go-version = "go1.8.3"
  # install = [ "./cmd/...", "./foo" ]
  ensure = "false"
  # additional-tools = ["github.com/mattes/migrate"]

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  name = "github.com/gorilla/mux"

[[constraint]]
  name = "github.com/stretchr/testify"
